language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch

deploy:
  provider: pypi
  user: "drewsonne"
  password: "Your password"
  distributions: "sdist bdist_wheel" # Your distributions here
  skip_cleanup: true
  on:
    tags: true
